Repository mautic/mautic-community-handbook, pull requests merged in 2024-10, with the labels that each got.

#234 Bump versions in requirements.txt
  docs/requirements.txt
Labels: dependencies, hacktoberfest-accepted

#233 Add legal and finance team
  docs/index.rst
  docs/links/legal_and_finance_team_slack.py
  docs/teams/legal_and_finance_team.rst
Labels: hacktoberfest-accepted

#238 fixed rst preview
  .github/holopin.yml
  .gitpod.Dockerfile
  .gitpod.yml
  .vscode/settings.json
  docs/conf.py
  docs/index.rst
  docs/overview/community.rst
  docs/requirements.txt
Labels: hacktoberfest-accepted

#241 Fix Vale linter
  .github/styles/config/vocabularies/Mautic/accept.txt
  .github/workflows/linting.yml
  .gitpod.yml
  .readthedocs.yaml
  docs/requirements.txt
Labels: bug, hacktoberfest-accepted

#239 Google summer of code
  .github/styles/config/vocabularies/Mautic/accept.txt
  docs/contributing/google_summer_of_code.rst
  docs/contributing/images/Summer_of_Code.png
  docs/index.rst
  docs/links/GSOC-ideas.py
  docs/links/GSOC-official-site.py
  docs/links/cc-by-sa3.py
  docs/links/mautic_assembly.py
  docs/links/mautic_contribution_guide.py
Labels: hacktoberfest-accepted, hacktoberfest

#240 Add theme styling to match Mautic branding
  docs/_templates/layout.html
  docs/css/theme.css
Labels: hacktoberfest-accepted

#244 Fix Vale linting entire directory
  .github/workflows/linting.yml
Labels: hacktoberfest-accepted
