Repository mautic/mautic-community-handbook, pull requests merged in 2025-02, with the labels that each got.

#247 Product-Team-Conversion
  .github/styles/config/vocabularies/Mautic/accept.txt
  docs/conf.py
  docs/contributing/mautic_bounty_programme.rst
  docs/index.rst
  docs/links/Mautic_pull_request_requirements.py
  docs/links/bounty_issues.py
  docs/links/bounty_project.py
  docs/links/idea_forum.py
  docs/links/mautic_community_partners.py
  docs/links/mautic_community_portal_roadmap.py
  docs/links/mautic_financial_policy.py
  docs/links/mautic_google_drive.py
  docs/links/mautic_mail.py
  docs/links/mautic_meeting_parser.py
  docs/links/mautic_product_team_slack.py
  docs/links/obs_model.py
  docs/links/open_collective.py
  docs/links/open_collective_organization.py
  docs/links/open_collective_payment_mtd.py
  docs/links/relevant_tax_forms.py
  docs/links/suicide_prevention_lifeline.py
  docs/policies/request_for_proposals_(RFP)_process.rst
  docs/teams/product_team/product_team_overview.rst
Labels: hacktoberfest-accepted

#251 added code of coduct
  .github/styles/config/vocabularies/Mautic/accept.txt
  docs/index.rst
  docs/links/creative_commons_attribution.py
  docs/links/mautic_email.py
  docs/links/mozilla_code_of_conduct.py
  docs/links/mozilla_community.py
  docs/policies/code_of_conduct/code_of_conduct.rst
Labels: ready-to-commit

#237 Added Community-to-RST #223
  .github/styles/config/vocabularies/Mautic/accept.txt
  docs/index.rst
  docs/links/code_of_conduct.py
  docs/links/community_portal.py
  docs/links/community_team_slack.py
  docs/links/international_country_forums.py
  docs/links/mautic_meetups_forum.py
  docs/links/mauticon_slack.py
  docs/links/partners_directory.py
  docs/links/savannah_crm.py
  docs/links/savannah_dashboard.py
  docs/teams/community_team/community_team.rst
  pages/09.community-team/.revs/20200310-170715/chapter.md
  pages/09.community-team/01.community-dashboard/.revs/20200310-170715/docs.md
  pages/09.community-team/02.meetup-guidelines/.revs/20200310-170715/docs.md
Labels: hacktoberfest-accepted, ready-to-commit

#245 Convert About section to RST
  docs/about/about.rst
  docs/about/what_is_mautic.rst
  docs/index.rst
  docs/links/mautic_documentation.py
  docs/links/mautic_trial.py
Labels: hacktoberfest-accepted, pending-feedback

#252 added code of conduct breaches
  docs/index.rst
  docs/policies/code_of_conduct/code_of_conduct_breaches.rst
Labels: ready-to-merge

#254 Update Leadership team page.md
  pages/04.community-leadership/01.current-leadership-team/docs.md
Labels: ready-to-merge

#255 Update current_leadership_team.rst
  docs/community_leadership/community_council.rst
  docs/community_leadership/community_leadership.rst
  docs/community_leadership/community_leadership_overview.rst
  docs/community_leadership/current_leadership_team.rst
  docs/community_leadership/leadership_role_definitions.rst
  docs/index.rst
  docs/links/mautic_governance.py
Labels: ready-to-merge
